# orchestrator_config.yaml

num_agents: 2
max_rounds: 1
environment_order:
#  - group_chat
#  - research
#  - web_research
  - prediction_markets
tool_mode: true
agent_config:
  knowledge_base: "hamlet_kb"
  use_llm: true
llm_configs:
    - name: "gpt-4o"
      model: "gpt-4o"
      client: "openai"
      max_tokens: 4096
      temperature: 0.7
      use_cache: true
#    - name: "claude"
#      model: "claude-3-5-sonnet-latest"
#      client: "anthropic"
#      max_tokens: 4096
#      temperature: 0.5
#      use_cache: true
#    - name: "hermes"
#      model: "openai/NousResearch/Hermes-3-Llama-3.1-8B"
#      client: "litellm"
#      max_tokens: 4096
#      temperature: 0.5
#      use_cache: true
#    - name: "deepseek"
#      model: "openai/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
#      client: "litellm"
#      max_tokens: 4096
#      temperature: 0.5
#      use_cache: true
#    - name: "qwq"
#      model: "openai/Qwen/QwQ-32B-Preview"
#      client: "litellm"
#      max_tokens: 4096
#      temperature: 0.5
#      use_cache: true
#    - name: "qwen"
#      model: "openai/Qwen/Qwen2.5-7B-Instruct"
#      client: "litellm"
#      max_tokens: 4096
#      temperature: 0.5
#      use_cache: true

environment_configs:
  group_chat:
    name: "group_chat"
    api_url: "http://localhost:8002"
  #  initial_topic: "Initial Market Discussion"
    initial_topic: "Hamlet's famous 'To be or not to be' soliloquy. Use emoji's and colloquial language for discussion"
    sub_rounds: 2
    group_size: 4

  research:
    name: "literary_research"
    api_url: "http://localhost:8003"
#    initial_topic: "Market Analysis"
    initial_topic: "Hamlet's famous 'To be or not to be' soliloquy', record your aha moments with emojis"
    sub_rounds: 2
    group_size: 4
    schema_model: "LiteraryAnalysis"

  prediction_markets:
    name: "prediction_markets"
    api_url: "http://localhost:8004"
    market_type: "CATEGORICAL"
    market: "What will be the Fed's rate decision in March 2024 FOMC meeting?"
    description: |
      This market predicts the exact size of the Federal Reserve's interest rate 
      decision at the March 2024 FOMC meeting. The current federal funds rate 
      target range is 5.25%-5.50%.
    resolution_criteria: |
      Market will resolve based on the size of the rate change announced in the 
      March 2024 FOMC statement:
      - No Change: Fed maintains current rates
      - 25 bps decrease: Fed cuts by exactly 0.25%
      - 50+ bps decrease: Fed cuts by 0.50% or more
      - 25+ bps increase: Fed raises rates by any amount
    resolution_date: "2024-03-20"
    initial_prices:
      "No Change": 0.972
      "25 bps decrease": 0.014
      "50+ bps decrease": 0.01
      "25+ bps increase": 0.004
    initial_liquidity: 12228577
    min_bet: 1.0
    max_bet: 100.0
    outcomes:
      - "No Change"
      - "25 bps decrease"
      - "50+ bps decrease"
      - "25+ bps increase"

#      # Market 2: Binary Outcome (Yes/No)
#      - name: "fed_march_50bps"
#        api_url: "http://localhost:8004"
#        market_type: "BINARY"
#        market: "Will the Fed cut rates by 50+ bps in March 2024?"
#        description: |
#          This market predicts whether the Federal Reserve will implement a rate cut 
#          of 50 basis points (0.50%) or larger at the March 2024 FOMC meeting.
#        resolution_criteria: |
#          Market resolves to YES if:
#          - The Fed cuts rates by 50 basis points (0.50%) or more
#          
#          Market resolves to NO if:
#          - The Fed makes no change to rates
#          - The Fed cuts by less than 50 bps
#          - The Fed raises rates
#        resolution_date: "2024-03-20"
#        initial_price: 0.01
#        initial_liquidity: 2883374
#        min_bet: 1.0
#        max_bet: 100.0
#        outcomes:
#          - "Yes"
#          - "No"

  web_research:
    name: "web_research"
    api_url: "http://localhost:8005"
    initial_query: "What will be the Fed's rate decision in March 2024 FOMC meeting?"
    sub_rounds: 1
    schema_model: "FedRateAnalysis"
    search_config:
      max_concurrent_requests: 50
      rate_limit: 0.1
      content_max_length: 4000
      request_timeout: 30
      urls_per_query: 2
      use_ai_summary: true
      methods: 
        - "selenium"
        - "playwright"
        - "beautifulsoup"
        - "newspaper3k"
        - "scrapy"
        - "requests_html"
        - "mechanicalsoup"
        - "httpx"
      default_method: "newspaper3k"
      headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"

protocol: "acl_message"
database_config:
  db_host: "localhost"
  db_port: "5433"

request_limits:
  openai:
    max_requests_per_minute: 500
    max_tokens_per_minute: 40000
  anthropic:
    max_requests_per_minute: 300
  vllm:
    max_requests_per_minute: 150
    max_tokens_per_minute: 50000
  litellm:
    max_requests_per_minute: 100
    max_tokens_per_minute: 35000